export const workspaceData = {
  featured: [
    {
      id: "1",
      title: "Digitalizing Logo",
      priority: "High",
      due: "Aug 12th, 2024",
      team: ["👤", "👤", "👤"],
      category: "Company Branding",
    },
    {
      id: "2",
      title: "Moodboard & Research",
      priority: "Low",
      due: "Aug 20th, 2024",
      team: ["👤", "👤"],
      category: "Company Branding",
    },
  ],
  projectOverview: [
    {
      id: "3",
      title: "Digital Campaign",
      tasks: "7 task",
      due: "Dec 23rd, 2024",
      status: "Pending",
    },
    {
      id: "4",
      title: "UI/UX Design",
      tasks: "12 task",
      due: "Oct 30th, 2024",
      status: "Pending",
    },
    {
      id: "5",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "15",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "6",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "7",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "8",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "90",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "50",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "55",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "554",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "544",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
    {
      id: "533",
      title: "Company Branding",
      tasks: "8 task",
      due: "Aug 25th, 2024",
      status: "On Going",
    },
  ],
};
